/* Wrapper header for bindgen FFI generation.
 * Include the minimal set of headers needed for core font manipulation.
 */

#include "fontforge-config.h"   /* generated by cmake */
#include "basics.h"
#include "splinefont.h"
#include "splineutil.h"
#include "splineutil2.h"
#include "splinechar.h"
#include "sd.h"
#include "sfd.h"
#include "start.h"
#include "splineoverlap.h"
#include "parsettf.h"
#include "tottf.h"
#include "fvfonts.h"
