// FontForge FFI bindings generated by bindgen at build time.
#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));

pub mod bdf;
pub mod ot_layout;
pub mod overlap;
pub mod pstype1;
pub mod svg;
pub mod ufo;
pub mod ufo_read;
