// Integration tests for TTF and OTF read/write round-trip via FFI.
// Mirrors tests/test_ttf_roundtrip.c:
//   Creates a SplineFont with 4 glyphs, writes TTF/OTF, reloads, verifies.

use std::ffi::CString;
use std::ptr;

const LY_FORE: isize = 1; // layer_type::ly_fore

/// Helper: create a rectangular contour (4 corners) and return the SplinePointList
unsafe fn make_rectangle(x: f64, y: f64, w: f64, h: f64) -> *mut fontforge_ffi::SplinePointList {
    let mut sp: [*mut fontforge_ffi::SplinePoint; 4] = [ptr::null_mut(); 4];
    let corners: [(f64, f64); 4] = [(x, y), (x + w, y), (x + w, y + h), (x, y + h)];
    for j in 0..4 {
        sp[j] = fontforge_ffi::SplinePointCreate(corners[j].0, corners[j].1);
        assert!(!sp[j].is_null());
    }
    fontforge_ffi::SplineMake(sp[0], sp[1], 0);
    fontforge_ffi::SplineMake(sp[1], sp[2], 0);
    fontforge_ffi::SplineMake(sp[2], sp[3], 0);
    fontforge_ffi::SplineMake(sp[3], sp[0], 0);

    let spl = libc::calloc(1, std::mem::size_of::<fontforge_ffi::SplinePointList>())
        as *mut fontforge_ffi::SplinePointList;
    assert!(!spl.is_null());
    (*spl).first = sp[0];
    (*spl).last = sp[0]; // Closed contour
    fontforge_ffi::SPLCategorizePoints(spl);
    spl
}

/// Create a standard test font with 4 glyphs (.notdef, A, B, C) each with
/// a 500x700 rectangular contour. Returns the font and its EncMap.
unsafe fn create_test_font(name: &str) -> (*mut fontforge_ffi::SplineFont, *mut fontforge_ffi::EncMap) {
    let sf = fontforge_ffi::SplineFontNew();
    assert!(!sf.is_null(), "SplineFontNew returned null");

    // Set font metadata
    let cname = CString::new(name).unwrap();
    if !(*sf).fontname.is_null() {
        libc::free((*sf).fontname as *mut libc::c_void);
    }
    (*sf).fontname = libc::strdup(cname.as_ptr());

    // Set SFD family/full name as well (some TTF code paths use these)
    (*sf).familyname = libc::strdup(cname.as_ptr());
    (*sf).fullname = libc::strdup(cname.as_ptr());

    // Set units-per-em (required for TTF output)
    (*sf).ascent = 800;
    (*sf).descent = 200;
    (*sf).design_size = 1000;

    // Create 4 glyphs: .notdef, A, B, C
    let glyphs: [(i32, &str); 4] = [
        (-1, ".notdef"),
        (0x0041, "A"),
        (0x0042, "B"),
        (0x0043, "C"),
    ];

    for &(uni, name_str) in &glyphs {
        let cname = CString::new(name_str).unwrap();
        let sc = fontforge_ffi::SFGetOrMakeChar(sf, uni, cname.as_ptr());
        assert!(!sc.is_null(), "SFGetOrMakeChar returned null for U+{:04X}", uni);

        let spl = make_rectangle(0.0, 0.0, 500.0, 700.0);
        let layer = (*sc).layers.offset(LY_FORE);
        (*layer).splines = spl;
    }

    let map = fontforge_ffi::EncMap1to1((*sf).glyphcnt);
    assert!(!map.is_null(), "EncMap1to1 returned null");

    (sf, map)
}

/// Check that a reloaded font has the expected TTF round-trip properties
unsafe fn verify_ttf_font(
    sf2: *mut fontforge_ffi::SplineFont,
    expected_name: &str,
    min_glyphs: i32,
) {
    assert!(!sf2.is_null(), "SFReadTTF returned null");

    // TTF reader may add extra glyphs (.null, nonmarkingreturn, etc.)
    assert!(
        (*sf2).glyphcnt >= min_glyphs,
        "expected at least {} glyphs, got {}",
        min_glyphs,
        (*sf2).glyphcnt
    );

    // Verify font name
    assert!(!(*sf2).fontname.is_null(), "fontname is null after reload");
    let reloaded = std::ffi::CStr::from_ptr((*sf2).fontname)
        .to_str()
        .unwrap_or("(invalid utf8)");
    assert_eq!(
        reloaded, expected_name,
        "font name mismatch: expected '{}', got '{}'",
        expected_name, reloaded
    );

    // Verify original 4 glyphs exist and have spline data (by name lookup)
    let glyph_names = [(-1, ".notdef"), (0x0041, "A"), (0x0042, "B"), (0x0043, "C")];
    for &(uni, name_str) in &glyph_names {
        let cname = CString::new(name_str).unwrap();
        let sc = fontforge_ffi::SFGetChar(sf2, uni, cname.as_ptr());
        assert!(
            !sc.is_null(),
            "glyph '{}' (U+{:04X}) not found after reload",
            name_str,
            if uni > 0 { uni as u32 } else { 0 }
        );
        let layer = (*sc).layers.offset(LY_FORE);
        assert!(
            !(*layer).splines.is_null(),
            "glyph '{}' has no spline data after reload",
            name_str
        );
    }
}

#[test]
fn test_ttf_roundtrip() {
    unsafe {
        fontforge_ffi::doinitFontForgeMain();

        let (sf, map) = create_test_font("TestFontTTF");

        let tmpfile = CString::new(format!("/tmp/fontforge_rs_ttf_{}.ttf", std::process::id()))
            .unwrap();

        // Write TTF: format=ff_ttf, no bitmaps, no hints, dummy DSIG, short PS names
        // ttf_flags values (not generated by bindgen due to shift expressions):
        //   ttf_flag_shortps = 1 << 0 = 1
        //   ttf_flag_nohints = 1 << 1 = 2
        //   ttf_flag_dummyDSIG = 1 << 15 = 32768
        let ttf_flags = (1 << 0) | (1 << 1) | (1 << 15);

        let ok = fontforge_ffi::WriteTTFFont(
            tmpfile.as_ptr() as *mut libc::c_char,
            sf,
            fontforge_ffi::fontformat_ff_ttf,
            ptr::null_mut(), // bsizes
            fontforge_ffi::bitmapformat_bf_none,
            ttf_flags,
            map,
            LY_FORE as i32,
        );
        assert!(ok != 0, "WriteTTFFont returned false for TTF format");

        // Free original font and map before reload
        fontforge_ffi::EncMapFree(map);
        fontforge_ffi::SplineFontFree(sf);

        // Reload from TTF
        let sf2 = fontforge_ffi::SFReadTTF(tmpfile.as_ptr() as *mut libc::c_char, 0, 0);
        verify_ttf_font(sf2, "TestFontTTF", 4);

        // Clean up
        fontforge_ffi::SplineFontFree(sf2);
        libc::unlink(tmpfile.as_ptr());

        println!("PASS: TTF round-trip test passed");
    }
}

#[test]
fn test_otf_roundtrip() {
    unsafe {
        fontforge_ffi::doinitFontForgeMain();

        let (sf, map) = create_test_font("TestFontOTF");

        let tmpfile = CString::new(format!("/tmp/fontforge_rs_otf_{}.otf", std::process::id()))
            .unwrap();

        // Write OTF: format=ff_otf, same flags as TTF
        let ttf_flags = (1 << 0) | (1 << 1) | (1 << 15);

        let ok = fontforge_ffi::WriteTTFFont(
            tmpfile.as_ptr() as *mut libc::c_char,
            sf,
            fontforge_ffi::fontformat_ff_otf,
            ptr::null_mut(), // bsizes
            fontforge_ffi::bitmapformat_bf_none,
            ttf_flags,
            map,
            LY_FORE as i32,
        );
        assert!(ok != 0, "WriteTTFFont returned false for OTF format");

        // Free original font and map before reload
        fontforge_ffi::EncMapFree(map);
        fontforge_ffi::SplineFontFree(sf);

        // Reload from OTF (SFReadTTF handles both TTF and OTF)
        let sf2 = fontforge_ffi::SFReadTTF(tmpfile.as_ptr() as *mut libc::c_char, 0, 0);
        verify_ttf_font(sf2, "TestFontOTF", 4);

        // Clean up
        fontforge_ffi::SplineFontFree(sf2);
        libc::unlink(tmpfile.as_ptr());

        println!("PASS: OTF round-trip test passed");
    }
}
