name: CI
on:
  push:
    branches: [ master, releases/** ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          path: repo
      - name: Restore cached custom dependencies
        id: cache-dependencies
        uses: actions/cache@v5
        with:
          path: deps/install
          key: ${{ runner.os }}-deps-${{ hashFiles('repo/.github/workflows/scripts/setup_linux_deps.sh') }}
      - name: Install dependencies and setup env vars
        run: ${{ github.workspace }}/repo/.github/workflows/scripts/setup_linux_deps.sh
      - name: Build FontForge library
        working-directory: repo
        run: |
          FFCONFIG="-DCMAKE_INSTALL_PREFIX=$PREFIX -DBUILD_SHARED_LIBS=ON"
          mkdir build && pushd build && cmake -GNinja $FFCONFIG .. && popd
          ninja -C build all install
      - name: Run FontForge tests
        run: CTEST_PARALLEL_LEVEL=100 ninja -C repo/build check
      - name: Build dist bundle
        run: ninja -C repo/build dist
      - name: Source archive artifact
        uses: actions/upload-artifact@v7
        with:
          name: source-archive
          path: repo/build/fontforge-*.tar.xz
